# Generated by Django 4.0.2 on 2022-03-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_projeto', models.CharField(blank=True, max_length=100)),
                ('descricao_projeto', models.TextField(blank=True)),
                ('imagen_projeto', models.ImageField(null=None, upload_to='media/Y%/m%')),
                ('github_projeto', models.URLField(blank=True)),
                ('link_projeto', models.URLField(null=None)),
            ],
        ),
    ]
