# Generated by Django 4.0.2 on 2022-03-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='descricao_projeto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='github_projeto',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='imagen_projeto',
            field=models.ImageField(blank=True, null=None, upload_to='media/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link_projeto',
            field=models.URLField(blank=True, null=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='titulo_projeto',
            field=models.CharField(max_length=100),
        ),
    ]
