# Generated by Django 4.0.2 on 2022-07-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0002_alter_projects_descricao_projeto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
