# Generated by Django 4.0.2 on 2022-07-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_contacts_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
