# Generated by Django 4.0.2 on 2022-07-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0004_alter_contacts_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('cont', models.IntegerField()),
            ],
        ),
    ]
