# Generated by Django 4.0.2 on 2022-07-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0005_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='cont',
        ),
    ]
